name: fiberchat #changing it will force you to change appname in import statement inside every .dart file.
description: Chats & Calling app

version: 2.0.7+77
publish_to: none

environment:
  sdk: ">=2.19.5 <4.0.0"

dependencies:
  logger: 1.4.0
  cloud_functions: ^4.3.4
  audioplayers: ^4.1.0
  pin_input_text_field: ^4.5.1
  audio_session: ^0.1.16
  flutter_cache_manager: ^3.3.1
  rxdart: ^0.27.7
  better_open_file: 3.6.4
  file_saver: ^0.2.6
  gallery_saver: 2.3.2
  url_launcher: ^6.1.12
  circular_countdown_timer: ^0.2.3
  camera: ^0.10.5+2
  oktoast: 3.3.1
  holding_gesture: 1.1.0
  flutter_emoji: 2.4.0
  pip_view: ^0.9.7
  page_transition: ^2.0.9
  wechat_assets_picker: ^8.5.0
  image_editor: ^1.0.2
  video_editor: ^1.4.3
  flutter_image_compress: ^1.1.0
  mime: ^1.0.4
  video_compress: 3.1.2
  link_preview_generator: 1.2.0
  google_mobile_ads: ^3.0.0
  font_awesome_flutter: ^10.5.0
  sms_autofill: ^2.3.0
  receive_sharing_intent: 1.4.5
  firebase_crashlytics: ^3.3.4
  async: ^2.11.0
  emoji_picker_flutter: ^1.6.1
  flutter_video_info: 1.3.1
  group_button: ^5.3.0
  flutter_colorpicker: ^1.0.3
  devicelocale: ^0.6.0
  http_auth: ^1.0.2
  cloud_firestore: ^4.8.3
  flutter_cached_pdfview: ^0.4.2
  firebase_messaging: ^14.6.5
  dio: ^5.3.0
  cached_network_image: ^3.2.3
  firebase_storage: ^11.2.5
  device_info_plus: ^8.2.2
  file_picker: ^5.2.10
  path_provider: ^2.0.15
  path: ^1.8.3
  flutter_sound: 9.2.13
  percent_indicator: ^4.2.3
  string_validator: ^1.0.0
  ntp: 2.0.0
  random_string: 2.3.1
  flutter_native_timezone: 2.0.0
  intl: ^0.18.0
  connectivity_plus: ^4.0.1
  http: ^0.13.6
  provider: ^6.0.5
  firebase_auth: ^4.7.1
  html: ^0.15.4
  image_picker: 0.8.7+1
  universal_platform: 1.0.0+1
  flutter_linkify: ^6.0.0
  dotted_border: ^2.0.0+3
  diacritic: ^0.1.4
  image_cropper: ^1.5.1
  contacts_service: 0.6.3
  share: 2.0.4
  scoped_model: ^2.0.0
  local_auth: ^2.1.6
  crypto: ^3.0.3
  encrypt: 5.0.1
  localstorage: ^4.0.1+4
  photo_view: ^0.14.0
  launch_review: 3.0.1
  overlay_support: ^2.1.0
  jiffy: ^6.2.1
  geolocator: ^9.0.2
  video_player: ^2.7.0
  video_thumbnail: 0.5.3
  chewie: ^1.5.0
  media_info: ^0.12.0+2
  firebase_core: ^2.15.0
  shared_preferences: ^2.2.0
  permission_handler: ^10.4.3
  agora_rtc_engine: ^6.1.1+1
  flutter_local_notifications: ^15.1.0+1
  flutter_secure_storage: ^8.0.0
  package_info_plus: ^3.1.2
  giphy_get: ^3.4.1
  wakelock: 0.6.2
  cupertino_icons: 1.0.5
  collection: ^1.17.1
  dropdown_plus: 0.0.9
  storage_manager: ^0.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
  flutter_driver:
    sdk: flutter
  test: ^1.16.8

  flutter_launcher_icons: ^0.13.1
flutter_icons:
  # android: "ic_launcher"
  ios: true
  image_path: "assets/appicon/appicon.jpg"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/sounds/
    - assets/flags/
    - lib/Services/localization/json_languages/
